# Generated by Django 2.2.2 on 2019-06-19 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_auto_20190619_0119'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Board',
            new_name='Task',
        ),
    ]
