# Generated by Django 2.2.2 on 2019-06-30 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0003_auto_20190622_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
